---
title: "Untitled"
author: "Joshua Catalano"
date: "July 22, 2018"
output: html_document
---
This notebook contains instructions for how to create the text files from the CSV. It is necessary to follow the instructions provided in the source_url. In order to use this function, you will need to create a folder that contains only the CSV file (show_description_unique.csv). In this case, I created a folder called show_description_unique_folder_with_csv_file. 

```{r setup, include=FALSE}

#loading the function to convert csv to text files

#NOTE READ DIRECTIONS FOR THIS FUNCTION AT URL
#windows users need Rtools installed, mac users need XCode installed

library(devtools)

source_url("https://gist.github.com/benmarwick/9266072/raw/csv2txts.R")

#The code for the function can be found below:

csv2txt <- function(mydir, labels = 1){
  
  # Get the names of all the CSV file
  mycsvfile <- list.files(mydir, full.names = TRUE, pattern = "*.CSV|.csv")
  
  # Read the actual contexts of the text files into R and rearrange a little.
  
  # create a list of dataframes containing the text
  mycsvdata <- read.csv(mycsvfile)
  
  # combine all except the first column together into
  # one long character string for each row
  mytxtsconcat <- apply(mycsvdata[-(1:labels)], 1, paste, collapse=" ")
  
  # make a dataframe with the file names and texts
  mytxtsdf <- data.frame(filename = mycsvdata[,labels], # get the first col for the text file names
                         fulltext = mytxtsconcat)
  
  # Now write one text file for each row of the csv
  # use 'invisible' so we don't see anything in the console
  
  setwd(mydir)
  invisible(lapply(1:nrow(mytxtsdf), function(i) write.table(mytxtsdf[i,2], 
                                                               file = paste0(mytxtsdf[i,1], ".txt"),
                                                               row.names = FALSE, col.names = FALSE,
                                                               quote = FALSE)))
  
  # now check your folder to see the txt files
  message(paste0("Your text files can be found in ", getwd()))
}
 

```


```{r}
# Providing the full path to the folder containing the csv file. Must have quotes and forward slashes. 

csv2txt("/Users/josh/Documents/CRDH_History/CRDH_history_channel/text_files", labels = 1)  

```
 
