---
title: "Untitled"
author: "Joshua Catalano"
date: "July 30, 2018"
output: html_document
---
```{r}
library(ggplot2)
```

The notebook contains the code used to make figure 3. 

```{r setup, include=FALSE}

count_table <- read.csv(file="~/Documents/CRDH_History/CRDH_history_channel/frequency_data.csv", header=TRUE, sep=",")

show_counts <- count_table %>% 
  count(Show.Name) %>% 
  group_by(Show.Name) %>% 
  mutate(show_count = n()) %>% 
  ungroup()

```



```{r}
figure_3 <- show_counts %>% 
  filter(Show.Name != c("999", "888")) %>%
  filter(Show.Name != "777") %>%
  top_n(15, n) %>%
ggplot(aes(x = reorder(Show.Name, - n),  y = n)) + 
  geom_bar(stat="identity", width=.5, fill="tomato3") + 
  labs(title="Total Number of Episodes, By Show, Aired on History, 5/15/18 - 6/13/18", x = "Show", y = "Number of episodes aired") + 
    theme(plot.title = element_text(hjust = 0.5, size = 18)) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1, size =12)) +
    theme(axis.title.y = element_text(size = 16)) +
    theme(axis.title.x = element_text(margin = margin(t = 15, r = 00, b = 8, l = 0))) +
    theme(axis.title.y = element_text(margin = margin(t = 0, r = 15, b = 0, l = 8))) +
    theme(plot.title = element_text(margin = margin(t = 15, r = 00, b = 15, l = 0))) +
    theme(axis.title.x = element_text(size = 16)) 
```

```{r}
ggsave("figure_3.png", plot = figure_3, height = 8, width = 11)
```

```{r}
#Formatting for figure 3 for LSU press
figure_3_1 <- show_counts %>% 
  filter(Show.Name != c("999", "888")) %>%
  filter(Show.Name != "777") %>%
  top_n(11, n) %>%
ggplot(aes(x = reorder(Show.Name, - n),  y = n)) + 
  geom_bar(stat="identity", width=.5, fill="grey40") + 
  labs(title="Total Number of Episodes, By Show, Aired on History, 5/15/18 - 6/13/18", x = "Show", y = "Number of episodes aired") + 
    theme(plot.title = element_text(hjust = 0.5, size = 14)) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1, size =12)) +
    theme(axis.title.y = element_text(size = 14)) +
    theme(axis.title.x = element_text(margin = margin(t = 15, r = 00, b = 8, l = 0))) +
    theme(axis.title.y = element_text(margin = margin(t = 0, r = 15, b = 0, l = 8))) +
    theme(plot.title = element_text(margin = margin(t = 15, r = 00, b = 15, l = 0))) +
    theme(axis.text.x = element_text(size = 12)) +
    theme(axis.text.y = element_text(size = 12)) +
    theme(axis.title.x = element_text(size = 14)) 
```
```{r}
ggsave("figure_3_1.jpg", plot = figure_3_1, height = 7, width = 7.5)
```

```{r}
episode_counts <- count_table %>% 
  count(Title) %>% 
  group_by(Title) %>% 
    ungroup()
  
colnames(episode_counts)[colnames(episode_counts)=="n"] <- "episode_count"

```

